### ISSUE TITLE
Fehler in drawPlayer wenn level < 0

### ISSUE THREAD

**Issue by karin112358** [bennyKi/rock-paper-scissors#1]
Wenn ein Spieler verliert, wird beim `level` 1 abgezogen. Möglicherweise wird das `level` dadurch < 0, was auch gewünscht ist. Dem Spieler wird dann die GAME OVER Message angezeigt.

Es wird allerdings weiterhin noch für eine Sekunde `drawPlayer` aufgerufen, bevor der Player zur Startseite weitergeleitet wird. In `drawPlayer` wird das Bild für den Player aufgerufen (z.B. `images.walk[player.level]`). Da das `level` aber schon < 0 ist, kommt es da zu einem Fehler.

Es wird dann folgender Fehler in der Console angezeigt:
![image](https://user-images.githubusercontent.com/9429286/113515154-0570fa80-9573-11eb-81eb-8b3e373ed6c8.png)

Du könntest entweder den Spieler gar nicht mehr anzeigen, wenn das `level` schon < 0 ist. Oder du nimmst dann das Bild mit dem Index 0.

**Comment by 11undefined11** [comment]
Liebe Karin,
könntest du mir nochmal helfen? Ich habe deinen Tipp befolgt und die Fehlermeldung ist verschwunden. Es ruckelt aber immer noch so komisch und in der Konsole wird ein komischer Fehler angezeigt: 
```
Uncaught TypeError: Cannot read property 'level' of undefined
    at index.js:410
```
Danke für deine Hilfe.

Liebe Grüße,
Benjamin
